###
GET http://localhost:3001/api/notifications/00b81614-3117-4bcd-9d79-cb6aecc0c02e
Accept: application/json

###
GET http://localhost:3001/api/health
Accept: application/json

###
GET http://localhost:3001/api/ready
Accept: application/json
#x-api-key: key here

###
POST http://localhost:3001/api/notifications/send
Content-Type: application/json
x-api-key: 12345678901234567890123456789012

{
  "email": "insoleg918@gmail.com",
  "subject": "Welcome to our service!",
  "htmlContent": "<h1>Hello TestUser!</h1><p>This is a notification email.</p>",
  "callbackUrl": "https://example.com/notifications/callback"
}
