import fs from 'fs';
import * as crypto from 'crypto';

export interface EnvAnswers {
  projectName: string;
  environment: 'development' | 'production';
  port: string;
  useDocker: boolean;
  dbHost?: string;
  dbPort?: string;
  dbUser?: string;
  dbPassword?: string;
  dbName: string;
  rabbitHost?: string;
  rabbitPort?: string;
  rabbitUser?: string;
  rabbitPassword?: string;
  smtpProvider: string;
  smtpHost?: string;
  smtpPort?: string;
  smtpUser: string;
  smtpPassword: string;
  senderEmail: string;
  enableRateLimit: boolean;
  redisUrl?: string;
  enableApiKey: boolean;
  apiKey?: string;
}

function generateApiKey(
  length: number = 32,
): string {
  try {
    const encoding = 'base64';
    return crypto.randomBytes(length).toString(encoding);
  } catch (err) {
    console.error('Error generating secret key:', err);
    process.exit(1);
  }
}

export function generateEnvFile(answers: EnvAnswers): string {
  const dbHost = answers.useDocker ? 'db' : answers.dbHost || 'localhost';
  const dbPort = answers.useDocker ? '5432' : answers.dbPort || '5432';
  const dbUser = answers.dbUser || 'postgres';
  const dbPassword = answers.dbPassword || 'postgres';

  const rabbitHost = answers.useDocker ? 'rabbitmq' : answers.rabbitHost || 'localhost';
  const rabbitPort = answers.useDocker ? '5672' : answers.rabbitPort || '5672';
  const rabbitUser = answers.rabbitUser || 'guest';
  const rabbitPassword = answers.rabbitPassword || 'guest';

  let smtpHost = answers.smtpHost || 'smtp.mailtrap.io';
  let smtpPort = answers.smtpPort || '2525';

  if (answers.smtpProvider === 'mailtrap') {
    smtpHost = 'smtp.mailtrap.io';
    smtpPort = '2525';
  } else if (answers.smtpProvider === 'gmail') {
    smtpHost = 'smtp.gmail.com';
    smtpPort = '587';
  }

  const apiKey = answers.enableApiKey ? answers.apiKey || generateApiKey() : '';

  return `# Generated by notification-service init
# ${new Date().toISOString()}

# Environment
NODE_ENV=${answers.environment}
PORT=${answers.port}
LOG_LEVEL=${answers.environment === 'production' ? 'info' : 'debug'}

# Database
DATABASE_URL=postgresql://${dbUser}:${dbPassword}@${dbHost}:${dbPort}/${answers.dbName}

# RabbitMQ
RABBITMQ_URL=amqp://${rabbitUser}:${rabbitPassword}@${rabbitHost}:${rabbitPort}

# SMTP
SMTP_HOST=${smtpHost}
SMTP_PORT=${smtpPort}
SMTP_USER=${answers.smtpUser}
SMTP_PASS=${answers.smtpPassword}
SENDER_EMAIL=${answers.senderEmail}

# Features
${answers.enableApiKey ? 'API_KEY=' + apiKey : ''}

${
  answers.enableRateLimit
    ? `# Rate Limiting
RATE_LIMIT_ENABLED=true
REDIS_URL=${answers.redisUrl}
RATE_LIMIT_MAX_REQUESTS=100
RATE_LIMIT_WINDOW_MS=60000`
    : ''
}

# Additional
PROJECT_NAME=${answers.projectName}
`;
}

export function writeEnvFile(content: string, filepath: string = '.env'): boolean {
  try {
    fs.writeFileSync(filepath, content, 'utf-8');
    return true;
  } catch (error) {
    console.error('Failed to write .env file:', error);
    return false;
  }
}
