import { SetupAnswers } from '../prompts/questions.js';

export function buildEnvTemplate(answers: SetupAnswers): string {
  const dbHost = answers.useDocker ? 'db' : answers.dbHost || 'localhost';
  const dbPort = answers.useDocker ? '5432' : answers.dbPort || '5432';
  const dbUser = answers.dbUser || 'postgres';
  const dbPassword = answers.dbPassword || 'postgres';

  const rabbitHost = answers.useDocker ? 'rabbitmq' : answers.rabbitHost || 'localhost';
  const rabbitPort = answers.useDocker ? '5672' : answers.rabbitPort || '5672';
  const rabbitUser = answers.rabbitUser || 'guest';
  const rabbitPassword = answers.rabbitPassword || 'guest';

  let smtpHost = answers.smtpHost || 'smtp.mailtrap.io';
  let smtpPort = answers.smtpPort || '2525';

  if (answers.smtpProvider === 'mailtrap') {
    smtpHost = 'smtp.mailtrap.io';
    smtpPort = '2525';
  } else if (answers.smtpProvider === 'gmail') {
    smtpHost = 'smtp.gmail.com';
    smtpPort = '587';
  }

  return [
    '# Generated by notification-service init',
    `# ${new Date().toISOString()}`,

    '',
    '# Environment',
    `NODE_ENV=${answers.environment}`,
    `PORT=${answers.port}`,
    `LOG_LEVEL=${answers.environment === 'production' ? 'info' : 'debug'}`,

    '',
    '# Database',
    `DATABASE_URL=postgresql://${dbUser}:${dbPassword}@${dbHost}:${dbPort}/${answers.dbName}`,

    '',
    '# RabbitMQ',
    `RABBITMQ_URL=amqp://${rabbitUser}:${rabbitPassword}@${rabbitHost}:${rabbitPort}`,
    'RABBITMQ_DLX_EXCHANGE=notification.dlx',
    'OUTBOUND_QUEUE_NAME=email_notifications',
    'OUTBOUND_DLQ_NAME=email.dlq',
    'OUTBOUND_DLQ_ROUTING_KEY=email.dlq',
    'OUTBOUND_RETRY_QUEUE_NAME=email.retry',
    'RABBITMQ_OUTBOUND_TTL=300000',
    'RABBITMQ_OUTBOUND_MAX_LENGTH=10000',

    '',
    '# SMTP',
    `SMTP_HOST=${smtpHost}`,
    `SMTP_PORT=${smtpPort}`,
    `SMTP_USER=${answers.smtpUser}`,
    `SMTP_PASS=${answers.smtpPassword}`,

    '',
    '# Features',
    answers.enableApiKey ? `API_KEY=${answers.apiKey}` : '',

    answers.enableRateLimit
      ? [
          '# Rate Limiting',
          'RATE_LIMIT_ENABLED=true',
          `REDIS_URL=${answers.redisUrl}`,
          'RATE_LIMIT_MAX_REQUESTS=100',
          'RATE_LIMIT_WINDOW_MS=60000',
        ].join('\n')
      : '',

    '',
    '# Additional',
    `PROJECT_NAME=${answers.projectName}`,
  ]
    .filter(Boolean)
    .join('\n');
}
